spring:
  profiles:
    active: dev
  application:
    name: ludotheque
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5000/realms/ludotheque
  data:
    mongodb:
#      username: root
#      password: root
      host: localhost
      port: 27017
      database: DEMO_ENI_Ecole
#      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  secret: MzJieXRlc2RlY29kZWVuYmFzZTY0cG91clNlY3JldEtleQ==
  expiration: 3600000  # en millisecondes (ici : 1h)