spring:
  profiles:
    active: dev
  application:
    name: ludotheque
  data:
    mongodb:
#      username: root
#      password: root
      host: localhost
      port: 27017
      database: DEMO_ENI_Ecole
#      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG