spring:
  application:
    name: ludotheque
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: DEMO_ENI_Ecole
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
